name: qrlog_frontend
version: 1.0.0+1
publish_to: none
description: A new Flutter application.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flame_splash_screen: ^0.1.0
  get_cli: ^1.8.1
  uni_links: ^0.5.1
  intl: ^0.17.0
  localstorage: ^4.0.0+1
  flutter_easyloading: ^3.0.5
  get: 4.6.5
  flutter_svg: ^1.1.1+1
  flutter_stripe: ^4.0.0
  url_launcher: ^6.1.5
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  qr_flutter: ^4.0.0
  switcher: ^1.0.0
  flutter_downloader: ^1.8.3
  url_launcher_web: ^2.0.13
  calendar_agenda: ^0.0.2+3
  dropdown_search: ^5.0.2


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/icons/
    - assets/icons/menu_icons/
    - assets/images/splash_screen.png
    - assets/images/splashscreen-web.png
    - assets/images/user.png
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
    - family: DigitalNumbers
      fonts:
        - asset: assets/fonts/digital_numbers/DigitalNumbersr.ttf
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/bebas_neue/BebasNeue-Regular.ttf


